spring:
    application:
        name: user-service

    datasource:
        url: jdbc:h2:mem:user-service
        driver-class-name: org.h2.Driver
        username: sa
        password: 
  
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: false
        properties:
          hibernate:
            format_sql: false
        
  
    h2:
        console:
            enabled: true
            path: /h2
            settings:
                web-allow-others: true

    custom:
        db:
          credentials:
            username: ${spring.datasource.username}
            password: ${spring.datasource.password}